name: Test GCLOUD_SERVICE_ACCOUNT Secret
on: [workflow_dispatch]  # Allows manual runs

jobs:
  verify-secret:
    runs-on: ubuntu-latest
    steps:
      # Basic existence check
      - name: Check secret exists
        run: |
          if [ -z "${{ secrets.GCLOUD_SERVICE_ACCOUNT }}" ]; then
            echo "❌ Error: Secret is missing or empty!"
            exit 1
          else
            echo "✅ Secret exists"
          fi

      # Validate JSON structure
      - name: Validate JSON
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > temp.json
          if jq -e . >/dev/null 2>&1 < temp.json; then
            echo "✅ Valid JSON structure"
            echo "Service Account: $(jq -r '.client_email' temp.json)"
          else
            echo "❌ Invalid JSON format!"
            exit 1
          fi
          rm -f temp.json  # Cleanup
