title: Walmart Cashback Pro
description: 15% grocery cashback for verified members
theme: jekyll-theme-primer
include: [".nojekyll"]
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default
      utm_source: organic
